### ISSUE TITLE
 Jupyter环境，render_notebook方法未能显示图片

### ISSUE THREAD

**Issue by xdnauly** [hustcc/PyG2Plot#18]
返回值类型为pyg2plot.helper.html.HTML

**Comment by hustcc** [comment]
> 返回值类型为pyg2plot.helper.html.HTML

是 lab 嘛？

**Comment by xdnauly** [comment]
render_notebook函数，Jupyter Lab 上不显示，jupyter notebook可以显示。

**Comment by hustcc** [comment]
v0.1.7 supported.
