### ISSUE TITLE
目前是否支持"animation"动画的设置？

### ISSUE THREAD

**Issue by FioraL** [hustcc/PyG2Plot#21]
目前是否支持"animation"动画的设置？
尝试加入了比如`  "animation": 'zoom-in',
  "duration": 20, 
  "delay": 5,`
的code，但没生效

**Comment by hustcc** [comment]
```py
{
  "animation": {
     xx, yy, zz
  }
}
```

可以参考 G2Plot 的 animation 配置文档。
