### ISSUE TITLE
G2 的 API 对于用 jinja2 渲染很不友好

### ISSUE THREAD

**Issue by sunhailin-Leo** [hustcc/PyG2Plot#6]
@hustcc
* 你应该考虑怎么用 `jinja2` 封装 `G2` 的 `js api`

**Comment by hustcc** [comment]
> @hustcc
> 
> * 你应该考虑怎么用 `jinja2` 封装 `G2` 的 `js api`

正在考虑中了，看到 pyecharts 使用的是 JSCode string 来，这个目前提供了， 但是在考虑怎么将 Python 的 function 转成 js 的 function string。

之前的 python  忘得差不多了，还要捡起来。

**Comment by sunhailin-Leo** [comment]
@hustcc 
* 我去年本来也想封装一套，后来看了一段时间就劝退了😂，最近还是折腾 `Echarts 5.X` 的 `pyecharts` 下一版本
* 个人给你个建议哈：你可以折腾这个 [cloud-charts](https://github.com/alibaba/cloud-charts)

**Comment by hustcc** [comment]
@sunhailin-Leo PyG2Plot 封装的是 G2Plot，这个是完全 object 形式配置的，只有一些 callback 是 function，所以可行。对于 G2，几乎全部是命令式的 API，太复杂了。

cloud-charts 和 G2Plot 思路相同，我都搞不懂 AntV 都官方封装配置的图表了，为啥阿里云还搞 🤔

**Comment by sunhailin-Leo** [comment]
@hustcc 
* Python 渲染一些 `js` 的 `function` 还是很难受的，写的时候得注意一些地方；除非能撸一个 AST 将 Python 的函数转换为 js 的 unction 🐶 
* 阿里云闲的蛋疼 😂😂

**Comment by hustcc** [comment]
@sunhailin-Leo  G2Plot 的知名度完全不如 echarts，所以项目运营难很多。还是你 6，pyecharts 都到 10k + 了

**Comment by sunhailin-Leo** [comment]
> @hustcc
> 
> * Python 渲染一些 `js` 的 `function` 还是很难受的，写的时候得注意一些地方；除非能撸一个 AST 将 Python 的函数转换为 js 的 unction 🐶
> * 阿里云闲的蛋疼 😂😂

* 草率了。。还真有这样的库 
    * https://github.com/metapensiero/metapensiero.pj
    * https://github.com/timothycrosley/jiphy

**Comment by sunhailin-Leo** [comment]
> @hustcc
> 
> * Python 渲染一些 `js` 的 `function` 还是很难受的，写的时候得注意一些地方；除非能撸一个 AST 将 Python 的函数转换为 js 的 unction 🐶
> * 阿里云闲的蛋疼 😂😂

* 草率了。。还真有这样的库 
    * https://github.com/metapensiero/metapensiero.pj
    * https://github.com/timothycrosley/jiphy

**Comment by sunhailin-Leo** [comment]
> @sunhailin-Leo G2Plot 的知名度完全不如 echarts，所以项目运营难很多。还是你 6，pyecharts 都到 10k + 了

* 主要还是 `Echarts` 好 😂，没有 `Echarts` 也没有 `pyecharts` 🐶

**Comment by hustcc** [comment]
> > @hustcc
> > 
> > * Python 渲染一些 `js` 的 `function` 还是很难受的，写的时候得注意一些地方；除非能撸一个 AST 将 Python 的函数转换为 js 的 unction 🐶
> > * 阿里云闲的蛋疼 😂😂
> 
> * 草率了。。还真有这样的库
>   
>   * https://github.com/metapensiero/metapensiero.pj
>   * https://github.com/timothycrosley/jiphy

所以可以搞起来了 🐶
